<?php
/**
 * Setup / Install Database E-Piket
 * Jalankan halaman ini sekali untuk menginisialisasi database
 */
session_start();

$message = '';
$error = '';
$step = $_GET['step'] ?? 'check';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host = $_POST['db_host'] ?? 'localhost';
    $user = $_POST['db_user'] ?? 'root';
    $pass = $_POST['db_pass'] ?? '';
    $name = $_POST['db_name'] ?? 'e_piket';
    
    // Test koneksi
    $conn = new mysqli($host, $user, $pass);
    if ($conn->connect_error) {
        $error = 'Koneksi gagal: ' . $conn->connect_error;
    } else {
        // Buat database
        $conn->query("CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci");
        $conn->select_db($name);
        
        // Jalankan SQL
        $sql_file = file_get_contents(__DIR__ . '/db/e_piket.sql');
        
        // Split per statement
        $statements = array_filter(array_map('trim', explode(';', $sql_file)));
        
        $success = 0;
        $failed = 0;
        
        foreach ($statements as $stmt) {
            if (empty($stmt)) continue;
            // Skip CREATE DATABASE and USE statements
            if (stripos($stmt, 'CREATE DATABASE') !== false) continue;
            if (stripos($stmt, 'USE ') !== false) continue;
            
            if ($conn->query($stmt)) {
                $success++;
            } else {
                $failed++;
            }
        }
        
        // Update config
        $config_content = "<?php\n";
        $config_content .= "// Konfigurasi Database - Auto-generated by Setup\n";
        $config_content .= "define('DB_HOST', '$host');\n";
        $config_content .= "define('DB_USER', '$user');\n";
        $config_content .= "define('DB_PASS', '" . addslashes($pass) . "');\n";
        $config_content .= "define('DB_NAME', '$name');\n";
        $config_content .= "?>";
        
        // Write config (not using file_put_contents for security, display manual instructions)
        $message = "Database '$name' berhasil dibuat!<br>";
        $message .= "Berhasil: $success statement | Gagal: $failed statement<br><br>";
        $message .= "<strong>Langkah selanjutnya:</strong><br>";
        $message .= "1. Buka file <code>config/database.php</code><br>";
        $message .= "2. Update konfigurasi database sesuai data di atas<br>";
        $message .= "3. Login dengan: <code>admin / password</code>";
        
        $step = 'done';
        $conn->close();
    }
}
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup - E-Piket</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        body {
            min-height: 100vh;
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-family: 'Segoe UI', sans-serif;
        }
        .setup-card {
            background: rgba(255,255,255,0.05);
            backdrop-filter: blur(20px);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 24px;
            padding: 48px;
            width: 100%;
            max-width: 500px;
            color: white;
        }
        .setup-card h1 {
            text-align: center;
            margin-bottom: 8px;
            font-size: 24px;
        }
        .setup-card .subtitle {
            text-align: center;
            color: rgba(255,255,255,0.5);
            margin-bottom: 32px;
        }
        .form-control, .form-select {
            background: rgba(255,255,255,0.08);
            border: 1px solid rgba(255,255,255,0.15);
            color: white;
        }
        .form-control:focus {
            background: rgba(255,255,255,0.12);
            border-color: #3b82f6;
            color: white;
            box-shadow: 0 0 0 3px rgba(59,130,246,0.2);
        }
        .form-label { color: rgba(255,255,255,0.7); }
        .btn-setup {
            width: 100%;
            padding: 14px;
            background: linear-gradient(135deg, #3b82f6, #8b5cf6);
            border: none;
            border-radius: 12px;
            color: white;
            font-weight: 600;
            font-size: 16px;
            cursor: pointer;
        }
        .btn-setup:hover { transform: translateY(-2px); box-shadow: 0 8px 24px rgba(59,130,246,0.4); }
        .alert-success-custom {
            background: rgba(34,197,94,0.15);
            border: 1px solid rgba(34,197,94,0.3);
            color: #86efac;
            border-radius: 12px;
            padding: 20px;
        }
        .alert-danger-custom {
            background: rgba(239,68,68,0.15);
            border: 1px solid rgba(239,68,68,0.3);
            color: #fca5a5;
            border-radius: 12px;
            padding: 20px;
        }
        code { background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="setup-card">
        <div class="text-center mb-4">
            <div style="font-size:48px;color:#3b82f6;margin-bottom:16px;">
                <i class="bi bi-gear-wide-connected"></i>
            </div>
            <h1>Setup E-Piket</h1>
            <p class="subtitle">Inisialisasi database aplikasi</p>
        </div>
        
        <?php if ($step === 'done'): ?>
            <div class="alert-success-custom">
                <i class="bi bi-check-circle-fill me-2"></i>
                <?= $message ?>
            </div>
            <div class="text-center mt-4">
                <a href="index.php" class="btn btn-setup">
                    <i class="bi bi-box-arrow-in-right me-2"></i>Login Sekarang
                </a>
            </div>
        <?php elseif ($step === 'check'): ?>
            <?php
            // Check if database is already configured (tanpa memicu die() dari getDB)
            $db_exists = false;
            $db_check_host = defined('DB_HOST') ? DB_HOST : null;
            if ($db_check_host) {
                $test = @new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
                if (!$test->connect_error) {
                    $res = @$test->query("SELECT COUNT(*) FROM users");
                    $db_exists = ($res !== false);
                }
                $test->close();
            }
            
            if ($db_exists): ?>
                <div class="alert-success-custom mb-4">
                    <i class="bi bi-check-circle-fill me-2"></i>
                    Database sudah terkonfigurasi dan dapat diakses.
                </div>
                <a href="index.php" class="btn btn-setup">
                    <i class="bi bi-box-arrow-in-right me-2"></i>Login
                </a>
            <?php else: ?>
                <div class="alert-danger-custom mb-4">
                    <i class="bi bi-exclamation-triangle me-2"></i>
                    Database belum terkonfigurasi. Silakan isi form di bawah untuk setup.
                </div>
                
                <?php if ($error): ?>
                <div class="alert-danger-custom mb-4">
                    <i class="bi bi-x-circle me-2"></i><?= $error ?>
                </div>
                <?php endif; ?>
                
                <form method="POST">
                    <div class="mb-3">
                        <label class="form-label">Database Host</label>
                        <input type="text" class="form-control" name="db_host" value="localhost">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Username</label>
                        <input type="text" class="form-control" name="db_user" value="root">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Password</label>
                        <input type="password" class="form-control" name="db_pass" value="">
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Nama Database</label>
                        <input type="text" class="form-control" name="db_name" value="e_piket">
                    </div>
                    <button type="submit" class="btn btn-setup">
                        <i class="bi bi-database-fill-gear me-2"></i>Setup Database
                    </button>
                </form>
            <?php endif; ?>
        <?php endif; ?>
        
        <div class="text-center mt-4">
            <small class="text-muted">&copy; 2026 E-Piket v1.0</small>
        </div>
    </div>
</body>
</html>
